const PROCEDURE_NAME = {
    SL_BORROWREVIEWLEVEL_CREATEORUPDATE: 'SL_BORROWREVIEWLEVEL_CreateOrUpdate_AdminWeb',
    SL_BORROWREVIEWLEVEL_APPLY_DEPARTMENT_CREATE: 'SL_BORROWREVIEWLEVEL_APPLY_DEPARTMENT_Create_AdminWeb',
    SL_BORROWREVIEWLEVEL_GETLIST: 'SL_BORROWREVIEWLEVEL_GetList_AdminWeb',
    SL_BORROWREVIEWLEVEL_GETUSERREVIEW: 'SL_BORROWREVIEWLEVEL_GetUserReview_AdminWeb',
    SL_BORROWTYPE_CREATEORUPDATE: 'SL_BORROWTYPE_CreateOrUpdate_AdminWeb',
    SL_BORROWTYPE_REVIEWLEVEL_DELETE: 'SL_BORROWTYPE_REVIEWLEVEL_Delete_AdminWeb',
    SL_BORROWTYPE_REVIEWLEVEL_CREATEORUPDATE: 'SL_BORROWTYPE_REVIEWLEVEL_CreateOrUpdate_AdminWeb',
    SL_BORROWTYPE_REVIEWLEVEL_USER_CREATEORUPDATE: 'SL_BORROWTYPE_REVIEWLEVEL_USER_CreateOrUpdate_AdminWeb',
    SL_BORROWTYPE_GETLIST: 'SL_BORROWTYPE_GetList_AdminWeb',
    SL_BORROWTYPE_GETBYID: 'SL_BORROWTYPE_GetById_AdminWeb',
    SL_BORROWTYPE_DELETE: 'SL_BORROWTYPE_Delete_AdminWeb',
};

module.exports = {
    PROCEDURE_NAME,
};
