export const defaultValues = {
    is_active: 1,
    shift_time: 0,
    shift_isovertime: 0,
    is_apply_monday:1,
    is_apply_tuesday:1,
    is_apply_wednesday:1,
    is_apply_thursday:1,
    is_apply_friday:1,
    is_check_store:0,
    is_break_shift: 0,
    is_support: 0,
    is_market_research: 0,
    is_training: 0,
}