const PROCEDURE_NAME = {
    MD_PRODUCT_GetList_StocksTake: 'MD_PRODUCT_GetList_StocksTake',
    SYS_USER_GetUserDepartment_AdminWeb: 'SYS_USER_GetUserDepartment_AdminWeb',
    ST_STOCKSTAKE_USER_CreateOrUpdate_AdminWeb: 'ST_STOCKSTAKE_USER_CreateOrUpdate_AdminWeb',
    ST_STOCKSTAKEREQUESTPERIOD_GetList: 'ST_STOCKSTAKEREQUESTPERIOD_GetList_AdminWeb',
    ST_STOCKSTAKEREQUESTPERIOD_CreateOrUpdate: 'ST_STOCKSTAKEREQUESTPERIOD_CreateOrUpdate_AdminWeb',
    ST_STOCKSTAKE_REVIEWLIST_Create_AdminWeb: 'ST_STOCKSTAKE_REVIEWLIST_Create_AdminWeb',
    ST_STOCKSTAKEREQUESTPERIOD_DeleteMaping_AdminWeb: 'ST_STOCKSTAKEREQUESTPERIOD_DeleteMaping_AdminWeb',
    ST_STOCKSTAKEREQUEST_GETBYID_ADMINWEB: 'ST_STOCKSTAKEREQUESTPERIOD_GetById_AdminWeb',
    ST_STOCKSTAKEREQUEST_GETBYIDEXECUTESTOCKSTAKE: 'ST_STOCKSTAKEREQUESTPERIOD_GetByIdExectuteStocksTake_AdminWeb',
    ST_STOCKSTAKE_PRODUCTLIST_CreateOrUpdate_AdminWeb: 'ST_STOCKSTAKE_PRODUCTLIST_CreateOrUpdate_AdminWeb',
    ST_STOCKSTAKEREQUESTPERIOD_TotalInventoryWithId: 'ST_STOCKSTAKEREQUESTPERIOD_TotalInventoryWithId_AdminWeb',
    ST_STOCKSTAKEPRODUCTLIST_IMEICODE_CreateOrUpdate_AdminWeb: 'ST_STOCKSTAKEPRODUCTLIST_IMEICODE_CreateOrUpdate_AdminWeb',
    ST_STOCKSTAKEPRODUCTLIST_IMEICODE_DeleteMapping_AdminWeb: 'ST_STOCKSTAKEPRODUCTLIST_IMEICODE_DeleteMapping_AdminWeb',
    ST_STOCKSTAKEREQUEST_CREATESTOCKSOUT:'ST_STOCKSTAKEREQUEST_CreateStocksOutDetail_AdminWeb',
    ST_STOCKSTAKEREQUEST_CREATESTOCKIN:'ST_STOCKSTAKEREQUESTPERIOD_CreateStocksIn_AdminWeb',
};

const ERROR_INVENTORY = {
    WAITREVIEW: 0,
    CHECKED: 1,
    ILLEGAL: 2,
};

const USERREVIEW_TYPES = {
    REJECT: 0, // k duyet
    APPROVED: 1, // da duyet
    WAIT: 2, // Tất cả hình thức
  };
  

module.exports = {
    PROCEDURE_NAME,
    ERROR_INVENTORY,
    USERREVIEW_TYPES
};
