const STORE_ANNOUNCECOMMENT = {
    ANNOUCECOMMNENT_GETLIST: 'SYS_ANNOUNCE_COMMENT_GetById_App',
    ANNOUCECOMMNENT_GETREPLYLIST: 'SYS_ANNOUNCE_COMMENT_GetListReplyById_App',
    ANNOUCECOMMNENT_GETDETAIL: 'SYS_ANNOUNCE_COMMENT_GetByCommentId_App',
    ANNOUCECOMMNENT_CREATEORUPDATE: 'SYS_ANNOUNCE_COMMENT_CreateOrUpdate_App',
    ANNOUCECOMMNENT_LIKE: 'SYS_ANNOUNCE_COMMENT_LIKE_CreateOrUpdate_App',
    ANNOUCECOMMNENT_DELETE: 'SYS_ANNOUNCE_COMMENT_Delete_App',
};

module.exports = {
    STORE_ANNOUNCECOMMENT,
};
