const NOTIFY = {
    OVERDUE_PAYMENT: 'OVERDUE_PAYMENT',
    ORDER_SHIPPED: 'ORDER_SHIPPED',
    ORDER_CANCELLED: 'ORDER_CANCELLED',
    ORDER_CREATED: 'ORDER_CREATED',
    QUOTATION_ORDER: 'QUOTATION_ORDER',
    QUOTATION_CANCELLED: 'QUOTATION_CANCELLED',
    QUOTATION_PENDING: 'QUOTATION_PENDING',
    QUOTATION_CREATED: 'QUOTATION_CREATED',
    QUOTATION_REJECTED: 'QUOTATION_REJECTED',
    QUOTATION_APPROVED: 'QUOTATION_APPROVED'
}

module.exports = NOTIFY;