module.exports = {
    NOT_FOUND: 'Requested resource not found.',
    VALIDATION_FAILED: 'Invalid request params.',
    REQUEST_SUCCESS: 'Request successfully!',
    REQUEST_FAILED: 'Something went wrong, please try again later.',
    AUTH: {
        EMAIL: {
            AVAILABLE: 'Email is available!',
            UNAVAILABLE: 'Email is not available.',
            FAIL_TO_SELECT: 'Having issue using selected email.',
        },
        LOGIN: {
            SUCCESS: 'Logged in successfully!',
            FAILED: 'Tên đăng nhập hoặc Mật khẩu đã nhập sai.',
            INACTIVE_USER: 'User account is inactive.',
            REFRESH_TOKEN_FAILED: 'Failed to request new session.',
            UNAUTHORIZED: 'Token invalid.',
            TOKEN_REQUIRED: 'Token is required.',
        },
        LOGOUT: {
            SUCCESS: 'Logged out successfully!',
        },
        CHANGE_PASSWORD: {
            SUCCESS: 'Password updated successfully!',
            FAILED: 'Failed to update password.',
        },
        FORGOT_PASSWORD: {
            INVALID_EMAIL: 'Account not found.',
            SUCCESS: 'Your request has successfully!',
            FAILED: 'Failed to forgot password.',
        },
    },
    PROFILE: {
        UPDATE_SUCCESS: 'Profile updated successfully!',
        UPDATE_FAILED: 'Failed to update profile.',
    },
    CRUD: {
        CREATE_SUCCESS: 'Create data successfully.',
        CREATE_FAILED: 'Create data failed.',
        UPDATE_SUCCESS: 'Update data successfully.',
        UPDATE_FAILED: 'Update data failed.',
        DELETE_SUCCESS: 'Delete data successfully.',
        UPLOAD_FAILED: 'Failed to upload image.',
    },
    USER: {
        VERIFICATION_SUCCESS: 'Account verification successfully!',
        VERIFICATION_FAILED: 'Account verification failed.',
        CREATE_SUCCESS: 'Create user success.',
        CREATE_FAILED: 'Create user failed.',
        UPDATE_SUCCESS: 'Update user success.',
        UPDATE_FAILED: 'Update user failed.',
        DELETE_SUCCESS: 'Delete user success.',
        UPDATE_PASSWORD_SUCCESS: 'Update password success.',
        GENERATE_USERNAME_SUCCESS: 'Generate username success.',
        OLD_PASSWORD_WRONG: 'Mật khẩu cũ không chính xác.',
        SAVEIMG_FAILED: 'Lỗi tải hình ảnh.',
    },
    USER_GROUP: {
        CREATE_SUCCESS: 'Create user group success.',
        CREATE_FAILED: 'Create user group failed.',
        UPDATE_SUCCESS: 'Update user group success.',
        UPDATE_FAILED: 'Update user group failed.',
        DELETE_SUCCESS: 'Delete user group success.',
        CHANGE_STATUS_SUCCESS: 'Change status user group success.',
        CHECK_NAME_FAILED: 'Tên nhóm người dùng đã tồn tại.',
    },
    USERGROUP_FUNCTION: {
        SAVE_SYS_USERGROUP_FUNCTION_SUCCESS: 'Save SYS_USERGROUP_FUNCTION is success',
        SAVE_SYS_USERGROUP_FUNCTION_FAILED: 'Save SYS_USERGROUP_FUNCTION is failed',
        DELETE_SYS_USERGROUP_FUNCTION_FAILED: 'Delete SYS_USERGROUP_FUNCTION is failed',
    },
    FUNCTION: {
        CREATE_SUCCESS: 'Create function success.',
        CREATE_FAILED: 'Create function failed.',
        UPDATE_SUCCESS: 'Update function success.',
        UPDATE_FAILED: 'Update function failed.',
        DELETE_SUCCESS: 'Delete function success.',
        CHANGE_STATUS_SUCCESS: 'Change status function success.',
        CHECK_ALIAS_FAILED: 'Mã hiệu quyền đã tồn tại.',
        CHECK_NAME_FAILED: 'Tên quyền đã tồn tại.',
    },
    FUNCTIONGROUP: {
        CREATE_SUCCESS: 'Create function group success.',
        CREATE_FAILED: 'Create function group failed.',
        UPDATE_SUCCESS: 'Update function group success.',
        UPDATE_FAILED: 'Update function group failed.',
        DELETE_SUCCESS: 'Delete function group success.',
        CHANGE_STATUS_SUCCESS: 'Change status function group success.',
        CHECK_NAME_FAILED: 'Tên nhóm quyền đã tồn tại.',
    },
    MENU: {
        CREATE_SUCCESS: 'Create menu success.',
        CREATE_FAILED: 'Create menu failed.',
        UPDATE_SUCCESS: 'Update menu success.',
        UPDATE_FAILED: 'Update menu failed.',
        DELETE_SUCCESS: 'Delete menu success.',
        CHANGE_STATUS_SUCCESS: 'Change status menu success.',
    },
    COMPANY: {
        CREATE_SUCCESS: 'Create company success.',
        CREATE_FAILED: 'Create company failed.',
        UPDATE_SUCCESS: 'Update company success.',
        UPDATE_FAILED: 'Update company failed.',
        DELETE_SUCCESS: 'Delete company success.',
        DELETE_FAILED: 'Delete company failed.',
        CHANGE_STATUS_SUCCESS: 'Change status company success.',
        CHECK_NAME: 'Tên công ty đã tồn tại.',
        CHECK_PHONE: 'Số điện thoại công ty đã tồn tại.',
        CHECK_EMAIL: 'Email công ty đã tồn tại.',
    },

    AMBUSINESSTYPE: {
        CREATE_SUCCESS: 'Create business type success.',
        CREATE_FAILED: 'Create business type failed.',
        UPDATE_SUCCESS: 'Update business type success.',
        UPDATE_FAILED: 'Update business type failed.',
        DELETE_SUCCESS: 'Delete business type success.',
        CHANGE_STATUS_SUCCESS: 'Change status business type success.',
        CHECK_NAME_FAILED: 'Tên loại miền đã tồn tại.',
    },

    CUSTOMERCOMMENTCARE: {
      CREATE_SUCCESS: 'Create customer comment success.',
      CREATE_FAILED: 'Create customer comment failed.',
      UPDATE_SUCCESS: 'Update customer comment success.',
      UPDATE_FAILED: 'Update customer comment failed.',
      DELETE_SUCCESS: 'Delete customer comment success.',
      CHANGE_STATUS_SUCCESS: 'Change status customer comment success.'
  },

    AMBUSINESS: {
        CREATE_SUCCESS: 'Create business success.',
        CREATE_FAILED: 'Create business failed.',
        UPDATE_SUCCESS: 'Update business success.',
        UPDATE_FAILED: 'Update business failed.',
        DELETE_SUCCESS: 'Delete business success.',
        CHANGE_STATUS_SUCCESS: 'Change status business success.',
        EXISTS_NAME: 'Tên miền đã tồn tại.',
    },

    CAMPAIGNSTATUS: {
        CREATE_SUCCESS: 'Create campaign status success.',
        CREATE_FAILED: 'Create campaign status failed.',
        UPDATE_SUCCESS: 'Update campaign status success.',
        UPDATE_FAILED: 'Update campaign status failed.',
        DELETE_SUCCESS: 'Delete campaign status success.',
        CHANGE_STATUS_SUCCESS: 'Change status campaign status success.',
        CHECK_NAME_FAILED: 'Tên trạng thái chiến dịch đã tồn tại.',
    },
    CAMPAIGNTYPE: {
        CREATE_SUCCESS: 'Create campaign type success.',
        CREATE_FAILED: 'Create campaign type failed.',
        CREATE_CAMPTYPE_RELEVEL_FAILED: 'Create campaign type review level failed.',
        UPDATE_SUCCESS: 'Update campaign type success.',
        UPDATE_FAILED: 'Update campaign type failed.',
        DELETE_SUCCESS: 'Delete campaign type success.',
        DELETE_CAMPTYPE_RELEVEL_FAILED: 'Delete campaign type review level failed.',
        CHANGE_STATUS_SUCCESS: 'Change status campaign type success.',
        DELETE_FAILED: 'Delete campaign type is failed',
    },

    CAMPAIGN: {
        CREATE_FAILED: 'Create campaign group failed.',
        CREATE_SUCCESS: 'Create campaign success.',
        UPDATED_FAILED_CAMPAIGN_APPROVED: 'Chiến dich không thể chỉnh sửa vì đã được duyệt.',
        DELETE_FAILED_CAMPAIGN_APPROVED: 'Chiến dich không thể xóa vì đã được duyệt.',
        DELETE_FAILED: 'Delete campaign is failed',
        DELETE_SUCCESS: 'Delete campaign success.',
    },

    CAMPAIGNREVIEWLIST: {
        DELETE_FAILED: 'Delete campaign review list is failed',
        CREATE_FAILED: 'Create campaign review list failed.',
        APPROVED_SUCCESS: 'Approved success.',
        APPROVED_FAILED: 'Approved failed.',
        DOUBLE_USER_REVIEW: 'Double user review.',
    },
    SEGMENT: {
        CREATE_SUCCESS: 'Create segment success.',
        CREATE_FAILED: 'Create segment failed.',
        UPDATE_SUCCESS: 'Update segment success.',
        UPDATE_FAILED: 'Update segment failed.',
        DELETE_SUCCESS: 'Delete segment success.',
        CHANGE_STATUS_SUCCESS: 'Change status segment success.',
        CHECK_NAME_FAILED: 'Tên phân khúc đã tồn tại.',
    },
    STATUSDATALEADS: {
        CREATE_SUCCESS: 'Create status dataleads success.',
        CREATE_FAILED: 'Create status dataleads failed.',
        UPDATE_SUCCESS: 'Update status dataleads success.',
        UPDATE_FAILED: 'Update status dataleads failed.',
        DELETE_SUCCESS: 'Delete status dataleads success.',
        CHANGE_STATUS_SUCCESS: 'Change status status dataleads success.',
    },
    AREA: {
        CREATE_SUCCESS: 'Create area success.',
        CREATE_FAILED: 'Create area failed.',
        UPDATE_SUCCESS: 'Update area success.',
        UPDATE_FAILED: 'Update area failed.',
        DELETE_SUCCESS: 'Delete area success.',
        CHANGE_STATUS_SUCCESS: 'Change status area success.',
    },
    STORE: {
        CREATE_SUCCESS: 'Create store success.',
        CREATE_FAILED: 'Create store failed.',
        UPDATE_SUCCESS: 'Update store success.',
        UPDATE_FAILED: 'Update store failed.',
        DELETE_SUCCESS: 'Delete store success.',
        CHANGE_STATUS_SUCCESS: 'Change status store success.',
    },
    STORETYPE: {
        CREATE_SUCCESS: 'Create store type success.',
        CREATE_FAILED: 'Create store type failed.',
        UPDATE_SUCCESS: 'Update store type success.',
        UPDATE_FAILED: 'Update store type failed.',
        DELETE_SUCCESS: 'Delete store type success.',
        CHANGE_STATUS_SUCCESS: 'Change status store type success.',
        EXISTS_NAME: 'Tên miền đã tồn tại.',
    },
    SUPPLIER: {
        CREATE_SUCCESS: 'Create supplier success.',
        CREATE_FAILED: 'Create supplier failed.',
        UPDATE_SUCCESS: 'Update supplier success.',
        UPDATE_FAILED: 'Update supplier failed.',
        DELETE_SUCCESS: 'Delete supplier success.',
        CHANGE_STATUS_SUCCESS: 'Change status supplier success.',
    },
    BANK: {
        CREATE_SUCCESS: 'Create bank success.',
        CREATE_FAILED: 'Create bank failed.',
        UPDATE_SUCCESS: 'Update bank success.',
        UPDATE_FAILED: 'Update bank failed.',
        DELETE_SUCCESS: 'Delete bank success.',
        CHANGE_STATUS_SUCCESS: 'Change status bank success.',
        EXISTS_NAME: 'Tên khối đã tồn tại.',
    },
    BLOCK: {
        CREATE_SUCCESS: 'Create block success.',
        CREATE_FAILED: 'Create block failed.',
        UPDATE_SUCCESS: 'Update block success.',
        UPDATE_FAILED: 'Update block failed.',
        DELETE_SUCCESS: 'Delete block success.',
        CHANGE_STATUS_SUCCESS: 'Change status block success.',
        EXISTS_NAME: 'Tên khối đã tồn tại.',
    },
    DEPARTMENT: {
        CREATE_SUCCESS: 'Create department success.',
        CREATE_FAILED: 'Create department failed.',
        UPDATE_SUCCESS: 'Update department success.',
        UPDATE_FAILED: 'Update department failed.',
        DELETE_SUCCESS: 'Delete department success.',
        CHANGE_STATUS_SUCCESS: 'Change status department success.',
        EXISTS_NAME: 'Tên phòng ban đã tồn tại.',
    },
    MANUFACTURER: {
        CREATE_SUCCESS: 'Create manufacturer success.',
        CREATE_FAILED: 'Create manufacturer failed.',
        UPDATE_SUCCESS: 'Update manufacturer success.',
        UPDATE_FAILED: 'Update manufacturer failed.',
        DELETE_SUCCESS: 'Delete manufacturer success.',
        CHANGE_STATUS_SUCCESS: 'Change status manufacturer success.',
        CHECK_NAME_FAILED: 'Tên nhà sản xuất đã tồn tại.',
        CHECK_CODE_FAILED: 'Mã nhà sản xuất đã tồn tại.',
    },
    TASKWORKFOLLOW: {
        CREATE_SUCCESS: 'Create task work follow success.',
        CREATE_FAILED: 'Create task work follow failed.',
        UPDATE_SUCCESS: 'Update task work follow success.',
        UPDATE_FAILED: 'Update task work follow failed.',
        DELETE_SUCCESS: 'Delete task work follow success.',
        CHANGE_STATUS_SUCCESS: 'Change status task work follow success.',
    },
    TASKTYPE: {
        CREATE_SUCCESS: 'Create task type success.',
        CREATE_FAILED: 'Create task type failed.',
        UPDATE_SUCCESS: 'Update task type success.',
        UPDATE_FAILED: 'Update task type failed.',
        DELETE_SUCCESS: 'Delete task type success.',
        DELETE_FAILED: 'Delete task type failed.',
        CHANGE_STATUS_SUCCESS: 'Change status task type success.',
    },
    BUSINESSUSER: {
        CREATE_SUCCESS: 'Create business user success.',
        CREATE_FAILED: 'Create business user failed.',
        UPDATE_SUCCESS: 'Update business user success.',
        UPDATE_FAILED: 'Update business user failed.',
        DELETE_SUCCESS: 'Delete business user success.',
        CHANGE_STATUS_SUCCESS: 'Change status business user success.',
    },
    TASK: {
        CREATE_SUCCESS: 'Thêm mới công việc thành công.',
        CREATE_FAILED: 'Thêm mới công việc thất bại.',
        UPDATE_SUCCESS: 'Cập nhật công việc thành công.',
        UPDATE_FAILED: 'Cập nhật công việc thất bại.',
        DELETE_SUCCESS: 'Xóa công việc thành công.',
        DELETE_FAILED: 'Xóa công việc thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái công việc thành công.',
    },
    DATALEADSCOMMENT: {
        CREATE_SUCCESS: 'Thêm mới bình luận thành công.',
        CREATE_FAILED: 'Thêm mới bình luận thất bại.',
        UPDATE_SUCCESS: 'Cập nhật bình luận thành công.',
        UPDATE_FAILED: 'Cập nhật bình luận thất bại.',
        DELETE_SUCCESS: 'Xóa bình luận thành công.',
        DELETE_FAILED: 'Xóa bình luận thất bại.',
    },
    FILEATTACTMENT: {
        UPLOAD_FAILED: 'Lưu đính kèm thất bại.',
        CREATE_SUCCESS: 'Thêm mới đính kèm thành công.',
        CREATE_FAILED: 'Thêm mới đính kèm thất bại.',
        UPDATE_SUCCESS: 'Cập nhật đính kèm thành công.',
        UPDATE_FAILED: 'Cập nhật đính kèm thất bại.',
        DELETE_SUCCESS: 'Xóa đính kèm thành công.',
        DELETE_FAILED: 'Xóa đính kèm thất bại.',
    },
    HISTORYDATALEADS: {
        CREATE_SUCCESS: 'Thêm mới lịch sử thành công.',
        CREATE_FAILED: 'Thêm mới lịch sử thất bại.',
        UPDATE_SUCCESS: 'Cập nhật lịch sử thành công.',
        UPDATE_FAILED: 'Cập nhật lịch sử thất bại.',
        DELETE_SUCCESS: 'Xóa lịch sử thành công.',
        DELETE_FAILED: 'Xóa lịch sử thất bại.',
    },
    DATALEADSMEETING: {
        CREATE_SUCCESS: 'Thêm mới cuộc hẹn thành công.',
        CREATE_FAILED: 'Thêm mới cuộc hẹn thất bại.',
        UPDATE_SUCCESS: 'Cập nhật cuộc hẹn thành công.',
        UPDATE_FAILED: 'Cập nhật cuộc hẹn thất bại.',
        DELETE_SUCCESS: 'Xóa cuộc hẹn thành công.',
        DELETE_FAILED: 'Xóa cuộc hẹn thất bại.',
    },
    CRM_CUSTOMERDATALEADS: {
        CREATE_FAILED: 'Create customer data leads failed.',
        CREATE_SUCCESS: 'Create customer data leads success.',
        DELETE_FAILED: 'Delete customer data leads is failed',
        DELETE_SUCCESS: 'Delete customer data leads success.',
        CHECK_IDCARD_FAILED: 'Chứng minh nhân dân đã tồn tại.',
        CHECK_PHONE_FAILED: 'Số điện thoại đã tồn tại.',
    },
    CRM_CUSCAMPAIGN: {
        CREATE_FAILED: 'Create customer campaign failed.',
        DELETE_FAILED: 'Delete customer campaign is failed',
    },
    CRM_SEG_DATALEADS: {
        CREATE_FAILED: 'Create seg data leads failed.',
        DELETE_FAILED: 'Delete seg data leads is failed',
    },
    DATALEADSSMS: {
        CREATE_SUCCESS: 'Thêm mới SMS thành công.',
        CREATE_FAILED: 'Thêm mới SMS thất bại.',
        UPDATE_SUCCESS: 'Cập nhật SMS thành công.',
        UPDATE_FAILED: 'Cập nhật SMS thành công.',
        DELETE_SUCCESS: 'Xóa SMS thành công.',
        DELETE_FAILED: 'Xóa SMS thành công.',
    },
    DATALEADSCALL: {
        CREATE_SUCCESS: 'Thêm mới cuộc gọi thành công.',
        CREATE_FAILED: 'Thêm mới cuộc gọi thất bại.',
        UPDATE_SUCCESS: 'Cập nhật cuộc gọi thành công.',
        UPDATE_FAILED: 'Cập nhật cuộc gọi thành công.',
        DELETE_SUCCESS: 'Xóa cuộc gọi thành công.',
        DELETE_FAILED: 'Xóa cuộc gọi thành công.',
    },
    TASKDATALEADS: {
        CHANGE_WORKFLOW_SUCCESS: 'Thay đổi bước xử lý thành công.',
        CHANGE_WORKFLOW_FAILED: 'Cập nhật bước xử lý thất bại.',
    },
    SENDSMS: {
        SENDSMS_SUCCESS: 'Gửi tin nhắn thành công.',
        SENDSMS_FAILED: 'Gửi tin nhắn thất bại',
        SENDSMS_CHECKCONNECTION_FAILED: 'Kết nối SMS thất bại.',
        SENDSMS_GETBRANDNAME_FAILED: 'Lấy danh sách Brandname lỗi.',
        SENDSMS_GETSERVICETYPELIST_FAILED: 'Lấy danh sách loại dịch vụ lỗi.',
    },
    DATALEADSMAIL: {
        CREATE_SUCCESS: 'Thêm mới mail thành công.',
        CREATE_FAILED: 'Thêm mới mail thất bại.',
        UPDATE_SUCCESS: 'Cập nhật mail thành công.',
        UPDATE_FAILED: 'Cập nhật mail thất bại.',
        DELETE_SUCCESS: 'Xóa mail thành công.',
        DELETE_FAILED: 'Xóa mail thất bại.',
    },
    PRODUCTCATEGORY: {
        CREATE_SUCCESS: 'Thêm mới ngành hàng thành công.',
        CREATE_FAILED: 'Thêm mới ngành hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật ngành hàng thành công.',
        UPDATE_FAILED: 'Cập nhật ngành hàng thất bại.',
        DELETE_SUCCESS: 'Xóa ngành hàng thành công.',
        DELETE_FAILED: 'Xóa ngành hàng thất bại.',
        SAVEIMG_FAILED: 'Lỗi tải hình ảnh.',
        EXISTS_NAME: 'Tên ngành hàng đã tồn tại.',
        EXISTS_SEO_NAME: 'Tên SEO đã tồn tại.',
    },
    PRODUCT: {
        CREATE_SUCCESS: 'Thêm mới sản phẩm thành công.',
        CREATE_FAILED: 'Thêm mới sản phẩm thất bại.',
        UPDATE_SUCCESS: 'Cập nhật sản phẩm thành công.',
        UPDATE_FAILED: 'Cập nhật sản phẩm thất bại.',
        DELETE_SUCCESS: 'Xóa sản phẩm thành công.',
        DELETE_FAILED: 'Xóa sản phẩm thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái sản phẩm thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái sản phẩm thất bại.',
        CHECK_CODE_FAILED: 'Mã sản phẩm đã tồn tại.',
        EXISTS_NAME: 'Tên sản phẩm đã tồn tại.',
        APPROVE_SUCCESS: 'Duyệt thành công.',
        APPROVE_EXITST: 'Mức duyệt đã được duyệt.',
        APPROVE_NOTEXITST: 'Mức duyệt không tồn tại.',
        APPROVE_UNNOW: 'Lỗi không xác định.',
    },
    PRODUCTATTRIBUTE: {
        CREATE_SUCCESS: 'Thêm mới thuộc tính sản phẩm thành công.',
        CREATE_FAILED: 'Thêm mới thuộc tính sản phẩm thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thuộc tính sản phẩm thành công.',
        UPDATE_FAILED: 'Cập nhật thuộc tính sản phẩm thất bại.',
        DELETE_SUCCESS: 'Xóa thuộc tính sản phẩm thành công.',
        DELETE_FAILED: 'Xóa thuộc tính sản phẩm thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thuộc tính sản phẩm thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thuộc tính sản phẩm thất bại.',
        EXISTS_NAME: 'Tên thuộc tính sản phẩm đã tồn tại.',
    },
    SL_PRICES: {
        CREATE_FAILED: 'Create price failed.',
        UPDATE_FAILED: 'Cập nhật lỗi!.',
        CREATE_SUCCESS: 'Create price success.',
        DELETE_FAILED: 'Delete price is failed',
        DELETE_SUCCESS: 'Delete price success.',
        CHANGE_STATUS_SUCCESS: 'Change status price success.',
        APPROVE_SUCCESS: 'Duyệt giá thành công.',
        APPROVE_EXITST: 'Giá đã được duyệt.',
        APPROVE_NOTEXITST: 'Mức duyệt không tồn tại.',
        APPROVE_UNNOW: 'Lỗi không xác định.',
        CHECK_TRUNG: 'Không được phép làm giá đồng thời: hình thức xuất, khu vực, miền, thời gian áp dụng',
        CHECK_DUPLICATES:
            'Không được phép làm giá đồng thời: hình thức xuất, khu vực, miền, đơn vị tính, thời gian áp dụng',
    },
    PROMOTION: {
        CREATE_SUCCESS: 'Thêm mới khuyến mãi thành công.',
        CREATE_FAILED: 'Thêm mới khuyến mãi thất bại.',
        UPDATE_SUCCESS: 'Cập nhật khuyến mãi thành công.',
        UPDATE_FAILED: 'Cập nhật khuyến mãi thất bại.',
        DELETE_SUCCESS: 'Xóa khuyến mãi thành công.',
        DELETE_FAILED: 'Xóa khuyến mãi thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái khuyến mãi thành công.',
        APPROVE_SUCCESS: 'Duyệt khuyến mãi thành công.',
    },
    PROMOTIONOFFER: {
        CREATE_SUCCESS: 'Thêm mới ưu đãi thành công.',
        CREATE_FAILED: 'Thêm mới ưu đãi thất bại.',
        UPDATE_SUCCESS: 'Cập nhật ưu đãi mãi thành công.',
        UPDATE_FAILED: 'Cập nhật ưu đãi thất bại.',
        DELETE_SUCCESS: 'Xóa ưu đãi thành công.',
        DELETE_FAILED: 'Xóa ưu đãi thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái ưu đãi thành công.',
        APPROVE_SUCCESS: 'Duyệt ưu đãi thành công.',
    },
    CUSTOMERTYPE: {
        CREATE_SUCCESS: 'Thêm mới loại khách hàng thành công.',
        CREATE_FAILED: 'Thêm mới loại khách hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật loại khách hàng thành công.',
        UPDATE_FAILED: 'Cập nhật loại khách hàng thất bại.',
        DELETE_SUCCESS: 'Xóa loại khách hàng thành công.',
        DELETE_FAILED: 'Xóa loại khách hàng thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái loại khách hàng thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái loại khách hàng thất bại.',
        CHECK_USED_FAILED: 'Loại khách hàng đã được sử dụng',
    },
    CUSTOMERCOMPANY: {
        CREATE_SUCCESS: 'Thêm mới công ty khách hàng thành công.',
        CREATE_FAILED: 'Thêm mới công ty khách hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật công ty khách hàng thành công.',
        UPDATE_FAILED: 'Cập nhật công ty khách hàng thất bại.',
        DELETE_SUCCESS: 'Xóa công ty khách hàng thành công.',
    },

    OUTPUTTYPE: {
        CREATE_SUCCESS: 'Thêm mới hình thức xuất thành công.',
        CREATE_FAILED: 'Thêm mới hình thức xuất thất bại.',
        UPDATE_SUCCESS: 'Cập nhật hình thức xuất thành công.',
        UPDATE_FAILED: 'Cập nhật hình thức xuất thất bại.',
        DELETE_SUCCESS: 'Xóa hình thức xuất thành công.',
        DELETE_FAILED: 'Xóa hình thức xuất thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái hình thức xuất thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái hình thức xuất thất bại.',
    },
    STATICCONTENT: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_TITLE: 'Tiêu đề đã tồn tại.',
        EXISTS_SEONAME: 'Đường dẫn đã tồn tại.',
        EXISTS_SYSTEMNAME: 'System name đã tồn tại.',
        EXISTS_METATITLE: 'MetaTitle đã tồn tại.',
        EXISTS_METAKEYWORD: 'MataKeyword đã tồn tại.',
    },
    NEWSCATEGORY: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_NAME: 'Tên chuyên mục đã tồn tại.',
        SAVEIMG_FAILED: 'Lỗi tải hình ảnh.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
        EXISTS_PARENT: 'Vui lòng xóa danh mục cấp con trước khi xóa danh mục cấp cha.',
    },
    TOPIC: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_NAME: 'Tên chủ đề đã tồn tại.',
    },
    SUPPORT: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },
    UPLOADFILE: {
        CREATE_SUCCESS: 'Upload tập tin thành công.',
        CREATE_ERROR: 'Upload tập tin thất bại.',
    },
    ACCOUNT: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        CHECK_USENAME_FAILED: 'Tên tài khoản đã được sử dụng',
        CHANGE_PASSWORD_SUCCESS: 'Thay đổi mật khẩu thành công.',
        CHANGE_PASSWORD_FAILED: 'Thay đổi mật khẩu thất bại.',
    },
    RECRUIT: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },
    BANNERTYPE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_PARENT: 'Vui lòng xóa danh mục cấp con trước khi xóa danh mục cấp cha.',
    },
    BANNER: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },
    DEGREE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },
    SKILLLEVEL: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },
    NEWSSTATUS: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_NAME: 'Tiêu đề đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
    },
    NEWS: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_NAME: 'Tiêu đề đã tồn tại.',
        UPLOAD_FAILED: 'Lưu ảnh thất bại.',
        EXISTS_TAG: 'Tag đã tồn tại.',
        EXISTS_METAKEYWORD: 'MataKeyword đã tồn tại.',
    },
    WEBSITECATEGORY: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_PARENT: 'Vui lòng xóa danh mục cấp con trước khi xóa danh mục cấp cha.',
        EXISTS_NAME: 'Tên danh mục đã tồn tại.',
    },
    CANDIDATE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },
    BOOKING: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },
    MEMBERSHIP: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },
    SETUPSERVICEREGISTER: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_PARENT: 'Vui lòng xóa danh mục cấp con trước khi xóa danh mục cấp cha.',
    },
    COMMENT: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_PARENT: 'Vui lòng xóa danh mục cấp con trước khi xóa danh mục cấp cha.',
    },
    CONTRACTTYPE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Chỉnh sửa thành công.',
        UPDATE_FAILED: 'Chỉnh sửa thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
    },
    CONTRACT: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Chỉnh sửa thành công.',
        UPDATE_FAILED: 'Chỉnh sửa thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
        APPROVED_SUCCESS: 'Duyệt thành công.',
        APPROVED_FAILED: 'Duyệt thất bại.',
        TRANSFER_SUCCESS: 'Chuyển nhượng thành công.',
        TRANSFER_FAILED: 'Chuyển nhượng thất bại.',
        FREEZE_SUCCESS: 'Bảo lưu thành công.',
        FREEZE_FAILED: 'Bảo lưu thất bại.',
    },
    HR_USER_TIMEKEEPING: {
        NOT_FOUND: 'Thông tin không tồn tại',
        APPROVED_SUCCESS: 'Duyệt thông tin thành công',
    },
    SETUPSERVICE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_PARENT: 'Vui lòng xóa danh mục cấp con trước khi xóa danh mục cấp cha.',
        UPLOAD_FAILED: 'Lưu ảnh thất bại.',
        EXISTS_METATITLE: 'MetaTitle đã tồn tại.',
        EXISTS_METAKEYWORD: 'MataKeyword đã tồn tại.',
    },
    ORDER: {
        CREATE_SUCCESS: 'Thêm mới đơn hàng thành công.',
        CREATE_FAILED: 'Thêm mới đơn hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật đơn hàng thành công.',
        UPDATE_FAILED: 'Cập nhật đơn hàng thất bại.',
        DELETE_SUCCESS: 'Xóa đơn hàng thành công.',
        DELETE_FAILED: 'Xóa đơn hàng thất bại.',
        SAVEIMG_FAILED: 'Lỗi tải hình ảnh.',
        CANCEL_FAILED: 'Hủy đơn hàng thất bại.',
        CANCEL_SUCCESS: 'Hủy đơn hàng thành công.',
        HOLDING_SUCCESS: 'Giữ hàng thành công.',
        HOLDING: 'Đang giữ hàng.',
        CREATE_STOCKSOUT_SUCCESS: 'Lập phiếu xuất hàng thành công.',
        CREATE_STOCKSOUT_FAILED: 'Lập phiếu xuất hàng thấ bại.',
    },
    COMPANY_TYPE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Chỉnh sửa thành công.',
        UPDATE_FAILED: 'Chỉnh sửa thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
        EXISTS_NAME: 'Tên loại hình công ty đã tồn tại.',
    },
    UNIT: {
        CREATE_SUCCESS: 'Thêm mới đơn vị tính thành công.',
        CREATE_FAILED: 'Thêm mới đơn vị tính thất bại.',
        UPDATE_SUCCESS: 'Cập nhật đơn vị tính thành công.',
        UPDATE_FAILED: 'Cập nhật đơn vị tính thất bại.',
        DELETE_SUCCESS: 'Xóa đơn vị tính thành công.',
        DELETE_FAILED: 'Xóa đơn vị tính thất bại.',
        EXISTS_NAME: 'Tên đơn vị đã tồn tại.',
    },
    POSITION: {
        CREATE_SUCCESS: 'Thêm mới chức vụ thành công.',
        CREATE_FAILED: 'Thêm mới chức vụ thất bại.',
        UPDATE_SUCCESS: 'Cập nhật chức vụ thành công.',
        UPDATE_FAILED: 'Cập nhật chức vụ thất bại.',
        DELETE_SUCCESS: 'Xóa chức vụ thành công.',
        DELETE_FAILED: 'Xóa chức vụ thất bại.',
        EXISTS_NAME: 'Tên chức vụ đã tồn tại.',
    },
    STOCKSINTYPE: {
        CREATE_SUCCESS: 'Thêm mới hình thức nhập thành công.',
        CREATE_FAILED: 'Thêm mới hình thức nhập thất bại.',
        UPDATE_SUCCESS: 'Cập nhật hình thức nhập thành công.',
        UPDATE_FAILED: 'Cập nhật hình thức nhập thất bại.',
        DELETE_SUCCESS: 'Xóa hình thức nhập thành công.',
        DELETE_FAILED: 'Xóa hình thức nhập thất bại.',
        EXISTS_NAME: 'Tên hình thức nhập đã tồn tại.',
    },
    STOCKSINTYPE: {
        CREATE_SUCCESS: 'Thêm mới hình thức nhập thành công.',
        CREATE_FAILED: 'Thêm mới hình thức nhập thất bại.',
        UPDATE_SUCCESS: 'Cập nhật hình thức nhập thành công.',
        UPDATE_FAILED: 'Cập nhật hình thức nhập thất bại.',
        DELETE_SUCCESS: 'Xóa hình thức nhập thành công.',
        DELETE_FAILED: 'Xóa hình thức nhập thất bại.',
        EXISTS_NAME: 'Tên hình thức nhập đã tồn tại.',
    },
    STOCKSTYPE: {
        CREATE_SUCCESS: 'Thêm mới loại kho thành công.',
        CREATE_FAILED: 'Thêm mới loại kho thất bại.',
        UPDATE_SUCCESS: 'Cập nhật loại kho thành công.',
        UPDATE_FAILED: 'Cập nhật loại kho thất bại.',
        DELETE_SUCCESS: 'Xóa loại kho thành công.',
        DELETE_FAILED: 'Xóa loại kho thất bại.',
        EXISTS_NAME: 'Tên hoặc mã loại kho đã tồn tại.',
    },
    PRODUCTHOLDING_CONFIG: {
        CREATE_SUCCESS: 'Thêm mới cấu hình giữ hàng thành công.',
        CREATE_FAILED: 'Thêm mới cấu hình giữ hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật cấu hình giữ hàng thành công.',
        UPDATE_FAILED: 'Cập nhật cấu hình giữ hàng thất bại.',
        DELETE_SUCCESS: 'Xóa cấu hình giữ hàng thành công.',
        DELETE_FAILED: 'Xóa cấu hình giữ hàng thất bại.',
        EXISTS_NAME: 'Tên cấu hình giữ hàng đã tồn tại.',
        CHECK_NAME: 'Đã tồn tại ngành hàng.',
    },
    STOCKSSTATUS: {
        CREATE_SUCCESS: 'Thêm mới trạng thái nhập xuất thành công.',
        CREATE_FAILED: 'Thêm mới trạng thái nhập xuất thất bại.',
        UPDATE_SUCCESS: 'Cập nhật trạng thái nhập xuất thành công.',
        UPDATE_FAILED: 'Cập nhật trạng thái nhập xuất thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa trạng thái nhập xuất thành công.',
        DELETE_FAILED: 'Xóa trạng thái nhập xuất thất bại.',
        EXISTS_NAME: 'Tên trạng thái nhập xuất đã tồn tại.',
    },
    STOCKSOUTTYPE: {
        CREATE_SUCCESS: 'Thêm mới hình thức phiếu xuất kho thành công.',
        CREATE_FAILED: 'Thêm mới hình thức phiếu xuất kho thất bại.',
        UPDATE_SUCCESS: 'Cập nhật hình thức phiếu xuất kho thành công.',
        UPDATE_FAILED: 'Cập nhật hình thức phiếu xuất kho thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa hình thức phiếu xuất kho thành công.',
        DELETE_FAILED: 'Xóa hình thức phiếu xuất kho thất bại.',
        EXISTS_NAME: 'Tên hình thức phiếu xuất kho đã tồn tại.',
    },
    STOCKS_REVIEW_LEVEL: {
        CREATE_SUCCESS: 'Thêm mới mức duyệt thành công.',
        CREATE_FAILED: 'Thêm mới mức duyệt thất bại.',
        UPDATE_SUCCESS: 'Cập nhật mức duyệt thành công.',
        UPDATE_FAILED: 'Cập nhật mức duyệt thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa mức duyệt thành công.',
        DELETE_FAILED: 'Xóa mức duyệt thất bại.',
        EXISTS_NAME: 'Tên mức duyệt đã tồn tại.',
    },

    ACCOUNTINGPERIOD: {
        CREATE_SUCCESS: 'Thêm mới kỳ kế toán thành công.',
        CREATE_FAILED: 'Thêm mới kỳ kế toán thất bại.',
        UPDATE_SUCCESS: 'Cập nhật kỳ kế toán thành công.',
        UPDATE_FAILED: 'Cập nhật kỳ kế toán thất bại.',
        DELETE_SUCCESS: 'Xóa kỳ kế toán thành công.',
        DELETE_FAILED: 'Xóa kỳ kế toán thất bại.',
        EXISTS_NAME: 'Tên kỳ kế toán đã tồn tại.',
        CHECK_NAME_FAILED: 'Tên kỳ kế toán đã tồn tại.',
    },
    STOCKSTAKETYPE: {
        CREATE_SUCCESS: 'Thêm mới hình thức kiểm kê kho thành công.',
        CREATE_FAILED: 'Thêm mới hình thức kiểm kê kho thất bại.',
        UPDATE_SUCCESS: 'Cập nhật hình thức kiểm kê kho thành công.',
        UPDATE_FAILED: 'Cập nhật hình thức kiểm kê kho thất bại.',
        DELETE_SUCCESS: 'Xóa hình thức kiểm kê kho thành công.',
        DELETE_FAILED: 'Xóa hình thức kiểm kê kho thất bại.',
        EXISTS_NAME: 'Tên hình thức kiểm kê kho đã tồn tại.',
    },
    RECEIVEEXPENDGROUP: {
        CREATE_SUCCESS: 'Thêm mới nhóm thu - chi thành công.',
        CREATE_FAILED: 'Thêm mới nhóm thu - chi thất bại.',
        UPDATE_SUCCESS: 'Cập nhật nhóm thu - chi thành công.',
        UPDATE_FAILED: 'Cập nhật nhóm thu - chi thất bại.',
        DELETE_SUCCESS: 'Xóa nhóm thu - chi thành công.',
        DELETE_FAILED: 'Xóa nhóm thu - chi thất bại.',
        EXISTS_NAME: 'Tên nhóm thu - chi đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
    },

    STOCKS_REVIEW_LEVEL: {
        CREATE_SUCCESS: 'Thêm mới mức duyệt thành công.',
        CREATE_FAILED: 'Thêm mới mức duyệt thất bại.',
        UPDATE_SUCCESS: 'Cập nhật mức duyệt thành công.',
        UPDATE_FAILED: 'Cập nhật mức duyệt thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa mức duyệt thành công.',
        DELETE_FAILED: 'Xóa mức duyệt thất bại.',
        EXISTS_NAME: 'Tên mức duyệt đã tồn tại.',
    },

    COSTTYPE: {
        CREATE_SUCCESS: 'Thêm mới loại chi phí thành công.',
        CREATE_FAILED: 'Thêm mới loại chi phí thất bại.',
        UPDATE_SUCCESS: 'Cập nhật loại chi phí thành công.',
        UPDATE_FAILED: 'Cập nhật loại chi phí thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa loại chi phí thành công.',
        DELETE_FAILED: 'Xóa loại chi phí thất bại.',
        EXISTS_NAME: 'Tên loại chi phí đã tồn tại.',
    },
    RECEIVETYPE: {
        CREATE_SUCCESS: 'Thêm mới loại thu thành công.',
        CREATE_FAILED: 'Thêm mới loại thu thất bại.',
        UPDATE_SUCCESS: 'Cập nhật loại thu thành công.',
        UPDATE_FAILED: 'Cập nhật loại thu thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa loại thu thành công.',
        DELETE_FAILED: 'Xóa loại thu thất bại.',
        EXISTS_NAME: 'Tên loại thu đã tồn tại.',
    },
    EXPEND_TYPE: {
        CREATE_SUCCESS: 'Thêm mới loại chi phí thành công.',
        CREATE_FAILED: 'Thêm mới loại chi phí thất bại.',
        UPDATE_SUCCESS: 'Cập nhật loại chi phí thành công.',
        UPDATE_FAILED: 'Cập nhật loại chi phí thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa loại chi phí thành công.',
        DELETE_FAILED: 'Xóa loại chi phí thất bại.',
        EXISTS_NAME: 'Tên loại chi phí đã tồn tại.',
        REVIEW_LEVEL: {
            CREATE_SUCCESS: 'Thêm mới mức duyệt thành công.',
            DELETE_SUCCESS: 'Xóa mức duyệt thành công.',
        },
    },
    PARTNERTRANSPORT: {
        CREATE_SUCCESS: 'Thêm mới đối tác vận chuyển thành công.',
        CREATE_DRIVER_SUCCESS: 'Thêm mới tài xế thành công',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
        EXISTS_NAME: 'Tên đã tồn tại.',
    },
    STOCKS: {
        CREATE_SUCCESS: 'Thêm mới kho hàng thành công.',
        CREATE_FAILED: 'Thêm mới kho hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật kho hàng thành công.',
        UPDATE_FAILED: 'Cập nhật kho hàng thất bại.',
        DELETE_SUCCESS: 'Xóa kho hàng thành công.',
        DELETE_FAILED: 'Xóa kho hàng thất bại.',
        EXISTS_NAME: 'Tên kho hàng đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
    },
    REQUESTPURCHASE: {
        CREATE_SUCCESS: 'Thêm mới yêu cầu mua hàng thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
        EXISTS_NAME: 'Tên đã tồn tại.',
    },

    STOCKSTAKEREQUESTPERIOD: {
        CREATE_SUCCESS: 'Thêm mới phiếu kiểm kê kho thành công.',
        CREATE_FAILED: 'Thêm mới phiếu kiểm kê kho thất bại.',
        UPDATE_SUCCESS: 'Cập nhật phiếu kiểm kê kho thành công.',
        UPDATE_FAILED: 'Cập nhật phiếu kiểm kê kho thất bại.',
        DELETE_SUCCESS: 'Xóa phiếu kiểm kê kho thành công.',
        DELETE_FAILED: 'Xóa phiếu kiểm kê kho thất bại.',
        EXISTS_NAME: 'Tên phiếu kiểm kê kho đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
    },
    PAYMENTSLIP: {
        CREATE_SUCCESS: 'Thêm mới phiếu chi thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
        EXISTS_NAME: 'Tên đã tồn tại.',
    },
    STOCKSINREQUEST: {
        CREATE_SUCCESS: 'Thêm mới phiếu nhập kho thành công.',
        CREATE_FAILED: 'Thêm mới phiếu nhập kho thất bại.',
        UPDATE_SUCCESS: 'Cập nhật phiếu nhập kho thành công.',
        UPDATE_FAILED: 'Cập nhật phiếu nhập kho thất bại.',
        DELETE_SUCCESS: 'Xóa phiếu nhập kho thành công.',
        DELETE_FAILED: 'Xóa phiếu nhập kho thất bại.',
        EXISTS_NAME: 'Tên phiếu nhập kho đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
        CREATE_COEFICIENT_SUCCESS: 'Thêm thành công',
        CREATE_COEFICIENT_FAILED: 'Thêm thất bại.',
        CHECK_QUANTITY_PURCHASE_ORDER: 'Số lượng nhập kho lớn hơn trong Số phiếu đơn mua hàng.',
        CHECK_LOTNUMBER_PURCHASE_ORDER: 'Số lô đã trùng với đơn hàng khác.',
        CREATE_PARTNER_SUCCESS: 'Thêm mới đơn vị vận chuyển thành công.',
        CREATE_PARTNER_FAILED: 'Thêm mới đơn vị vận chuyển thất bại.',
        EXISTS_CODE: 'Mã cuộn đã tồn tại trong kho.',
    },
    CRM_PARTNER: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
        EXISTS_NAME: 'Tên DN đã tồn tại.',
        EXISTS_PHONENUMBER: 'Số điện thoại DN đã tồn tại.',
        EXISTS_EMAIL: 'Email DN đã tồn tại.',
        EXISTS_PARTNERCODE: 'Mã khách hàng DN đã tồn tại.',
    },
    STOCKSOUTREQUEST: {
        CREATE_SUCCESS: 'Thêm mới phiếu xuất kho thành công.',
        CREATE_FAILED: 'Thêm mới phiếu xuất kho thất bại.',
        UPDATE_SUCCESS: 'Cập nhật phiếu xuất kho thành công.',
        UPDATE_FAILED: 'Cập nhật phiếu xuất kho thất bại.',
        DELETE_SUCCESS: 'Xóa phiếu xuất kho thành công.',
        DELETE_FAILED: 'Xóa phiếu xuất kho thất bại.',
        EXISTS_NAME: 'Tên phiếu xuất kho đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
        CREATE_OUTPUTTED_SUCCESS: 'Thêm mới phiếu xuất kho và xuất kho thành công.',
        CREATE_OUTPUTTED_FAILED: 'Thêm mới phiếu xuất kho và xuất kho  thành công.',
        CREATE_PARTNER_SUCCESS: 'Thêm mới đơn vị vận chuyển thành công.',
        CREATE_PARTNER_FAILED: 'Thêm mới đơn vị vận chuyển thất bại.',
    },
    MODEL: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        CHECK_CODE_FAILED: 'Mã đã tồn tại.',
    },
    ANNOUNCE_TYPE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_NAME: 'Tên loại thông báo đã tồn tại.',
        REVIEW_LEVEL: {
            CREATE_SUCCESS: 'Thêm mới mức duyệt thành công.',
            DELETE_SUCCESS: 'Xóa mức duyệt thành công.',
        },
    },

    ANNOUNCE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_NAME: 'Tên loại thông báo đã tồn tại.',
        REVIEW_SUCCESS: 'Duyệt thành công.',
    },
    SYS_NOTIFYTYPE: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_TITLE: 'Tên loại thông báo đã tồn tại.',
        EXISTS_PRIORITY: 'Thứ tự hiển thị đã tồn tại.',
    },
    SYS_NOTIFY: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
    },

    PURCHASEORDER: {
        CREATE_SUCCESS: 'Thêm mới đơn mua hàng thành công.',
        CREATE_FAILED: 'Thêm mới đơn mua hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật đơn mua hàng thành công.',
        UPDATE_FAILED: 'Cập nhật đơn mua hàng thất bại.',
        DELETE_SUCCESS: 'Xóa đơn mua hàng thành công.',
        DELETE_FAILED: 'Xóa đơn mua hàng thất bại.',
        EXISTS_NAME: 'Tên đơn mua hàng đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
    },
    APPCONFIG: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
        EXISTS_NAME: 'Tên đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
    },
    RECEIVESLIP: {
        CREATE_SUCCESS: 'Thêm mới phiếu thu thành công.',
        CREATE_FAILED: 'Thêm mới phiếu thu thất bại.',
        UPDATE_SUCCESS: 'Cập nhật phiếu thu thành công.',
        UPDATE_FAILED: 'Cập nhật phiếu thu thất bại.',
        DELETE_SUCCESS: 'Xóa phiếu thu thành công.',
        DELETE_FAILED: 'Xóa phiếu thu thất bại.',
        EXISTS_NAME: 'Tên phiếu thu đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
        GETPICTURES_SUCCESS: 'Cập nhật phiếu thu thành công.',
    },

    RECEIVESLIP_ORDER: {
        CREATE_FAILED: 'Thêm mới thông tin đơn hàng thất bại.',
    },

    ANNOUNCE_REVIEW_LEVEL: {
        CREATE_SUCCESS: 'Thêm mới mức duyệt thành công.',
        CREATE_FAILED: 'Thêm mới mức duyệt thất bại.',
        UPDATE_SUCCESS: 'Cập nhật mức duyệt thành công.',
        UPDATE_FAILED: 'Cập nhật mức duyệt thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa mức duyệt thành công.',
        DELETE_FAILED: 'Xóa mức duyệt thất bại.',
        EXISTS_NAME: 'Tên mức duyệt đã tồn tại.',
    },

    STOCKSTRANSFERTYPE: {
        CREATE_SUCCESS: 'Thêm mới hình thức phiếu chuyển kho thành công.',
        CREATE_FAILED: 'Thêm mới hình thức phiếu chuyển kho thất bại.',
        UPDATE_SUCCESS: 'Cập nhật hình thức phiếu chuyển kho thành công.',
        UPDATE_FAILED: 'Cập nhật hình thức phiếu chuyển kho thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa hình thức phiếu chuyển kho thành công.',
        DELETE_FAILED: 'Xóa hình thức phiếu chuyển kho thất bại.',
        EXISTS_NAME: 'Tên hình thức phiếu chuyển kho đã tồn tại.',
    },
    STOCKS_DETAIL: {
        DELETE_SUCCESS: 'Xóa thành công.',
        DELETE_FAILED: 'Xóa thất bại.',
    },
    AGEDEBITCONFIG: {
        CREATE_SUCCESS: 'Thêm mới tuổi nợ thành công.',
        CREATE_FAILED: 'Thêm mới tuổi nợ thất bại.',
        UPDATE_SUCCESS: 'Cập nhật tuổi nợ thành công.',
        UPDATE_FAILED: 'Cập nhật tuổi nợ thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa tuổi nợ thành công.',
        DELETE_FAILED: 'Xóa tuổi nợ thất bại.',
        EXISTS_NAME: 'Tên tuổi nợ đã tồn tại.',
    },

    CUSTOMERSTOCKS: {
        CREATE_SUCCESS: 'Create customer stocks success.',
        CREATE_FAILED: 'Create customer stocks failed.',
        UPDATE_SUCCESS: 'Update customer stocks success.',
        UPDATE_FAILED: 'Update customer stocks failed.',
        DELETE_SUCCESS: 'Delete customer stocks success.',
        DELETE_FAILED: 'Delete customer stocks failed.',
        CHANGE_STATUS_SUCCESS: 'Change status customer stocks success.',
        CHECK_NAME: 'Tên công ty đã tồn tại.',
        CHECK_PHONE: 'Số điện thoại công ty đã tồn tại.',
        CHECK_EMAIL: 'Email công ty đã tồn tại.',
    },

    PRICE_QUOTE: {
        CREATE_SUCCESS: 'Thêm mới báo giá thành công.',
        CREATE_FAILED: 'Thêm mới báo giá thất bại.',
        UPDATE_SUCCESS: 'Cập nhật báo giá thành công.',
        UPDATE_FAILED: 'Cập nhật báo giá thất bại.',
        DELETE_SUCCESS: 'Xóa báo giá thành công.',
        DELETE_FAILED: 'Xóa báo giá thất bại.',
        EXISTS_NAME: 'Số điện thoại đã tồn tại.',
        CREATE_CUSTOMERSTOCKS_SUCCESS: 'Thêm mới kho khách hàng thành công.',
        CREATE_CUSTOMERSTOCKS_FAILED: 'Thêm mới kho khách hàng thất bại.',
        CANCEL_SUCCESS: 'Hủy báo giá thành công.',
        CANCEL_FAILED: 'Hủy báo giá thất bại.',
        ON_HOLDING: 'Báo giá đang được giữ hàng',
        CREATE_ORDER_FAILED: 'Tạo đơn hàng không thành công',
        CREATE_ORDER_SUCCESS: 'Tạo đơn hàng thành công',
    },

    STOCKSTRANSFER: {
        CREATE_SUCCESS: 'Thêm mới phiếu chuyển kho thành công.',
        CREATE_FAILED: 'Thêm mới phiếu chuyển kho thất bại.',
        UPDATE_SUCCESS: 'Cập nhật phiếu chuyển kho thành công.',
        UPDATE_FAILED: 'Cập nhật phiếu chuyển kho thất bại.',
        DELETE_SUCCESS: 'Xóa phiếu chuyển kho thành công.',
        DELETE_FAILED: 'Xóa phiếu chuyển kho thất bại.',
        APPROVE_SUCCESS: 'Duyệt thành công.',
        APPROVE_EXITST: 'Mức duyệt đã được duyệt.',
        APPROVE_NOTEXITST: 'Mức duyệt không tồn tại.',
        APPROVE_UNNOW: 'Lỗi không xác định.',
        CANCEL_FAILED: 'Hủy thất bại.',
        CANCEL_SUCCESS: 'Hủy thành công.',
        TRANSFER_FAILED: 'Điều chuyển thất bại.',
        TRANSFER_SUCCESS: 'Điều chuyển thành công.',
    },
    MATERIAL: {
        CREATE_SUCCESS: 'Thêm mới túi bao bì thành công.',
        CREATE_FAILED: 'Thêm mới túi bao bì thất bại.',
        UPDATE_SUCCESS: 'Cập nhật túi bao bì thành công.',
        UPDATE_FAILED: 'Cập nhật túi bao bì thất bại.',
        DELETE_SUCCESS: 'Xóa túi bao bì thành công.',
        DELETE_FAILED: 'Xóa túi bao bì thất bại.',
        EXISTS_CODE: 'Mã túi bao bì đã tồn tại.',
    },
    SERVICE: {
        CREATE_SUCCESS: 'Thêm mới dịch vụ thành công.',
        CREATE_FAILED: 'Thêm mới dịch vụ thất bại.',
        UPDATE_SUCCESS: 'Cập nhật dịch vụ thành công.',
        UPDATE_FAILED: 'Cập nhật dịch vụ thất bại.',
        DELETE_SUCCESS: 'Xóa dịch vụ thành công.',
        DELETE_FAILED: 'Xóa dịch vụ thất bại.',
        EXISTS_NAME: 'Tên dịch vụ đã có trong hệ thống.',
        SAVEIMG_FAILED: 'Lỗi tải hình ảnh.',
    },
    PRODUCT_GIFT_CATEGORY: {
        CREATE_SUCCESS: 'Thêm mới danh mục quà tặng thành công.',
        CREATE_FAILED: 'Thêm mới danh mục quà tặng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật danh mục quà tặng thành công.',
        UPDATE_FAILED: 'Cập nhật danh mục quà tặng thất bại.',
        DELETE_SUCCESS: 'Xóa danh mục quà tặng thành công.',
        DELETE_FAILED: 'Xóa danh mục quà tặng thất bại.',
        EXISTS_NAME: 'Tên danh mục quà tặng đã có trong hệ thống.',
        SAVEIMG_FAILED: 'Lỗi tải hình ảnh.',
    },
    PRODUCTREGISTER: {
        CREATE_SUCCESS: 'Thêm mới thành công.',
        CREATE_FAILED: 'Thêm mới thất bại.',
        UPDATE_SUCCESS: 'Cập nhật thành công.',
        UPDATE_FAILED: 'Cập nhật thất bại.',
        DELETE_SUCCESS: 'Xóa thành công.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        EXISTS_PARENT: 'Vui lòng xóa danh mục cấp con trước khi xóa danh mục cấp cha.',
    },
    VAT: {
        CREATE_SUCCESS: 'Thêm mới VAT thành công.',
        CREATE_FAILED: 'Thêm mới VAT thất bại.',
        UPDATE_SUCCESS: 'Cập nhật VAT thành công.',
        UPDATE_FAILED: 'Cập nhật VAT thất bại.',
        DELETE_SUCCESS: 'Xóa VAT thành công.',
        DELETE_FAILED: 'Xóa VAT thất bại.',
        EXISTS_NAME: 'Tên VAT đã tồn tại.',
    },
    PRICEREVIEWLEVEL: {
        CREATE_SUCCESS: 'Thêm mới mức duyệt cho hình thức xuất bán thành công.',
        CREATE_FAILED: 'Thêm mới mức duyệt cho hình thức xuất bán thất bại.',
        UPDATE_SUCCESS: 'Cập nhật mức duyệt cho hình thức xuất bán thành công.',
        UPDATE_FAILED: 'Cập nhật mức duyệt cho hình thức xuất bán thất bại.',
        DELETE_SUCCESS: 'Xóa mức duyệt cho hình thức xuất bán thành công.',
        DELETE_FAILED: 'Xóa mức duyệt cho hình thức xuất bán thất bại.',
        EXISTS_NAME: 'Tên mức duyệt cho hình thức xuất bán đã tồn tại.',
    },
    ORIGIN: {
        CREATE_SUCCESS: 'Thêm mới xuất xứ thành công.',
        CREATE_FAILED: 'Thêm mới xuất xứ thất bại.',
        UPDATE_SUCCESS: 'Cập nhật xuất xứ thành công.',
        UPDATE_FAILED: 'Cập nhật xuất xứ thất bại.',
        DELETE_SUCCESS: 'Xóa xuất xứ thành công.',
        DELETE_FAILED: 'Xóa xuất xứ thất bại.',
        EXISTS_NAME: 'Tên xuất xứ đã tồn tại.',
    },
    CUSTOMERTYPEGROUP: {
        CREATE_SUCCESS: 'Thêm mới nhóm loại khách hàng thành công.',
        CREATE_FAILED: 'Thêm mới nhóm loại khách hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật nhóm loại khách hàng thành công.',
        UPDATE_FAILED: 'Cập nhật nhóm loại khách hàng thất bại.',
        DELETE_SUCCESS: 'Xóa nhóm loại khách hàng thành công.',
        DELETE_FAILED: 'Xóa nhóm loại khách hàng thất bại.',
        EXISTS_NAME: 'Tên nhóm loại khách hàng đã tồn tại.',
    },
    OFFWORKRL: {
        CREATE_SUCCESS: 'Create off work review level success.',
        CREATE_FAILED: 'Create off work review level failed.',
        UPDATE_SUCCESS: 'Update off work review level success.',
        UPDATE_FAILED: 'Update off work review level failed.',
        DELETE_SUCCESS: 'Delete off work review level success.',
        CHANGE_STATUS_SUCCESS: 'Change status off work review level success.',
    },
    COMPONENTGROUP: {
        CREATE_SUCCESS: 'Thêm mới nhóm linh kiện thành công.',
        CREATE_FAILED: 'Thêm mới nhóm linh kiện thất bại.',
        UPDATE_SUCCESS: 'Cập nhật nhóm linh kiện thành công.',
        UPDATE_FAILED: 'Cập nhật nhóm linh kiện thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái thất bại.',
        DELETE_SUCCESS: 'Xóa nhóm linh kiện thành công.',
        DELETE_FAILED: 'Xóa nhóm linh kiện thất bại.',
        EXISTS_NAME: 'Tên nhóm linh kiện đã tồn tại.',
    },
    SOLUTION: {
        CREATE_SUCCESS: 'Thêm mới giải pháp sửa chữa thành công.',
        CREATE_FAILED: 'Thêm mới giải pháp sửa chữa thất bại.',
        UPDATE_SUCCESS: 'Cập nhật giải pháp sửa chữa thành công.',
        UPDATE_FAILED: 'Cập nhật thuộc tính sản phẩm thất bại.',
        DELETE_SUCCESS: 'Xóa giải pháp sửa chữa thành công.',
        DELETE_FAILED: 'Xóa giải pháp sửa chữa thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái giải pháp sửa chữa thành công.',
        CHANGE_STATUS_FAILED: 'Thay đổi trạng thái giải pháp sửa chữa thất bại.',
        EXISTS_NAME: 'Tên giải pháp sửa chữa đã tồn tại.',
    },
    REQUEST: {
        CREATE_SUCCESS: 'Thêm mới phiếu yêu cầu thành công.',
        CREATE_FAILED: 'Thêm mới phiếu yêu cầu thất bại.',
        UPDATE_SUCCESS: 'Cập nhật phiếu yêu cầu thành công.',
        UPDATE_FAILED: 'Cập nhật phiếu yêu cầu thất bại.',
        DELETE_SUCCESS: 'Xóa phiếu yêu cầu thành công.',
        DELETE_FAILED: 'Xóa phiếu yêu cầu thất bại.',
    },
    RELATIONSHIP: {
        CREATE_SUCCESS: 'Thêm mới mối quan hệ thành công.',
        CREATE_FAILED: 'Thêm mới mối quan hệ thất bại.',
        UPDATE_SUCCESS: 'Cập nhật mối quan hệ thành công.',
        UPDATE_FAILED: 'Cập nhật mối quan hệ thất bại.',
        DELETE_SUCCESS: 'Xóa mối quan hệ thành công.',
        DELETE_FAILED: 'Xóa mối quan hệ thất bại.',
    },

    CRM_CUSTOMERCONTACT: {
        EXISTS_PHONENUMBER: 'Số điện thoại đã tồn tại.',
        EXISTS_EMAIL: 'Email đã tồn tại.',
    },
    PO_DISCOUNTPROGRAM: {
        CREATE_SUCCESS: 'Thêm mới chiết khấu thành công.',
        CREATE_FAILED: 'Thêm mới chiết khấu thất bại.',
        UPDATE_SUCCESS: 'Cập nhật chiết khấu thành công.',
        UPDATE_FAILED: 'Cập nhật chiết khấu thất bại.',
        DELETE_SUCCESS: 'Xóa chiết khấu thành công.',
        DELETE_FAILED: 'Xóa chiết khấu thất bại.',
        CHANGE_STATUS_SUCCESS: 'Thay đổi trạng thái chiết khấu thành công.',
        APPROVE_SUCCESS: 'Duyệt chiết khấu thành công.',
    },
    PURCHASECOST: {
        CREATE_SUCCESS: 'Thêm mới chi phí mua hàng thành công.',
        CREATE_FAILED: 'Thêm mới chi phí mua hàng thất bại.',
        UPDATE_SUCCESS: 'Cập nhật chi phí mua hàng thành công.',
        UPDATE_FAILED: 'Cập nhật chi phí mua hàng thất bại.',
        DELETE_SUCCESS: 'Xóa chi phí mua hàng thành công.',
        DELETE_FAILED: 'Xóa chi phí mua hàng thất bại.',
        EXISTS_NAME: 'Tên chi phí mua hàng đã tồn tại.',
        EXISTS_ORDERINDEX: 'Thứ tự hiển thị đã tồn tại.',
    },
    DOCUMENTTYPE: {
        CREATE_SUCCESS: 'Thêm mới loại hồ sơ thành công.',
        CREATE_FAILED: 'Thêm mới loại hồ sơ thất bại.',
        UPDATE_SUCCESS: 'Cập nhật loại hồ sơ thành công.',
        UPDATE_FAILED: 'Cập nhật loại hồ sơ thất bại.',
        DELETE_SUCCESS: 'Xóa loại hồ sơ thành công.',
        DELETE_FAILED: 'Xóa loại hồ sơ thất bại.',
        EXISTS_NAME: 'Tên loại hồ sơ đã tồn tại.',
    },
};
