export default {
  // #region position
  GET_TYPES_REQUEST: 'GET_TYPES_REQUEST',
  GET_TYPES_SUCCESS: 'GET_TYPES_SUCCESS',
  GET_TYPES_FAILURE: 'GET_TYPES_FAILURE',

  GET_TYPE_REQUEST: 'GET_TYPE_REQUEST',
  GET_TYPE_SUCCESS: 'GET_TYPE_SUCCESS',
  GET_TYPE_FAILURE: 'GET_TYPE_FAILURE',

  CREATE_TYPE_REQUEST: 'CREATE_TYPE_REQUEST',
  CREATE_TYPE_SUCCESS: 'CREATE_TYPE_SUCCESS',
  CREATE_TYPE_FAILURE: 'CREATE_TYPE_FAILURE',

  UPDATE_TYPE_REQUEST: 'UPDATE_TYPE_REQUEST',
  UPDATE_TYPE_SUCCESS: 'UPDATE_TYPE_SUCCESS',
  UPDATE_TYPE_FAILURE: 'UPDATE_TYPE_FAILURE',

  DELETE_TYPE_REQUEST: 'DELETE_TYPE_REQUEST',
  DELETE_TYPE_SUCCESS: 'DELETE_TYPE_SUCCESS',
  DELETE_TYPE_FAILURE: 'DELETE_TYPE_FAILURE',
  //#endregion
};
