export const CUSTOMER_CARE_LIST = {
  "items": [
      {
          "member_id": "540359",
          "customer_code": "SM22121300001                                     ",
          "full_name": "Bùi Duy Tiên",
          "gender": 1,
          "birth_day": "06/05/1998",
          "phone_number": "0865175951",
          "customer_type_name": "Khách hàng hạng kim cương",
          "customer_type_id": 1055,
          "address_full": "46 Cửu Long, Phường 02, Quận Tân Bình, Thành phố Hồ Chí Minh",
          "type_register": null,
          "is_active": 1,
          "email": "han@blackwind.vn",
          "status_data_leads_key": "IN_PROCESS",
          "status_data_leads_name": "Đang xử lý",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 31,
          "number_product_order": 31,
          "source_name": "Tại cửa hàng",
          "anni_ver": null,
          "time_final_buy": "22/12/2022",
          "customer_care_type_name": "Chăm sóc lâu chưa mua"
      },
      {
          "member_id": "540338",
          "customer_code": "KH22111600004",
          "full_name": "Lê Đình Chung",
          "gender": 1,
          "birth_day": "02/01/2018",
          "phone_number": "0986352356",
          "customer_type_name": "Khách hàng mới",
          "customer_type_id": 4056,
          "address_full": "Gg, Xã Mường Mùn, Huyện Tuần Giáo, Tỉnh Điện Biên",
          "type_register": null,
          "is_active": 1,
          "email": "lethiphuonghumg@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": null,
          "time_final_buy": null,
          "customer_care_type_name": "adasd"
      },
      {
          "member_id": "540338",
          "customer_code": "KH22111600004",
          "full_name": "Lê Đình Chung",
          "gender": 1,
          "birth_day": "02/01/2018",
          "phone_number": "0986352356",
          "customer_type_name": "Khách hàng mới",
          "customer_type_id": 4056,
          "address_full": "Gg, Xã Mường Mùn, Huyện Tuần Giáo, Tỉnh Điện Biên",
          "type_register": null,
          "is_active": 1,
          "email": "lethiphuonghumg@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": null,
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "540337",
          "customer_code": "KH22111600003",
          "full_name": "Chị Hân",
          "gender": 0,
          "birth_day": "01/01/1900",
          "phone_number": "0369964365",
          "customer_type_name": "Khách hàng mới",
          "customer_type_id": 4056,
          "address_full": "Yên Phụ, Phường Trúc Bạch, Quận Ba Đình, Thành phố Hà Nội",
          "type_register": null,
          "is_active": 1,
          "email": "hanhan@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": null,
          "time_final_buy": null,
          "customer_care_type_name": "adasd"
      },
      {
          "member_id": "540337",
          "customer_code": "KH22111600003",
          "full_name": "Chị Hân",
          "gender": 0,
          "birth_day": "01/01/1900",
          "phone_number": "0369964365",
          "customer_type_name": "Khách hàng mới",
          "customer_type_id": 4056,
          "address_full": "Yên Phụ, Phường Trúc Bạch, Quận Ba Đình, Thành phố Hà Nội",
          "type_register": null,
          "is_active": 1,
          "email": "hanhan@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": null,
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "520313",
          "customer_code": "SM22062700001                                     ",
          "full_name": "Nguyễn Thị Hân ",
          "gender": 0,
          "birth_day": "27/06/1998",
          "phone_number": "0987645650",
          "customer_type_name": "Khách hàng mới",
          "customer_type_id": 4056,
          "address_full": "23, Phường Phúc Tân, Quận Hoàn Kiếm, Thành phố Hà Nội, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "hn1@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Website",
          "anni_ver": null,
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "510314",
          "customer_code": "SM22062000002                                     ",
          "full_name": "Nguyendinhhung",
          "gender": 1,
          "birth_day": "02/07/1990",
          "phone_number": "0345847624",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": null,
          "type_register": null,
          "is_active": 1,
          "email": "admintest1123@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": null,
          "time_final_buy": null,
          "customer_care_type_name": "adasd"
      },
      {
          "member_id": "510314",
          "customer_code": "SM22062000002                                     ",
          "full_name": "Nguyendinhhung",
          "gender": 1,
          "birth_day": "02/07/1990",
          "phone_number": "0345847624",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": null,
          "type_register": null,
          "is_active": 1,
          "email": "admintest1123@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": null,
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "490313",
          "customer_code": "SM22053000001                                     ",
          "full_name": "staff",
          "gender": 1,
          "birth_day": "02/12/2001",
          "phone_number": "0652398741",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Phường Tứ Liên, Quận Tây Hồ, Thành phố Hà Nội, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "staff.b@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "adasd"
      },
      {
          "member_id": "490313",
          "customer_code": "SM22053000001                                     ",
          "full_name": "staff",
          "gender": 1,
          "birth_day": "02/12/2001",
          "phone_number": "0652398741",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Phường Tứ Liên, Quận Tây Hồ, Thành phố Hà Nội, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "staff.b@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "490313",
          "customer_code": "SM22053000001                                     ",
          "full_name": "staff",
          "gender": 1,
          "birth_day": "02/12/2001",
          "phone_number": "0652398741",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Phường Tứ Liên, Quận Tây Hồ, Thành phố Hà Nội, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "staff.b@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      },
      {
          "member_id": "490312",
          "customer_code": "SM22052500003                                     ",
          "full_name": "Michael",
          "gender": 1,
          "birth_day": "02/05/2002",
          "phone_number": "0365412987",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Phường Hàng Buồm, Quận Hoàn Kiếm, Thành phố Hà Nội",
          "type_register": null,
          "is_active": 1,
          "email": "staff.h@gmail.com",
          "status_data_leads_key": "ASSIGNED",
          "status_data_leads_name": "Đã phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Website",
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      },
      {
          "member_id": "470310",
          "customer_code": "SM22051100002                                     ",
          "full_name": "Test sổ địa chỉ",
          "gender": 0,
          "birth_day": "05/11/2022",
          "phone_number": "0989787656",
          "customer_type_name": "Khách hàng mới",
          "customer_type_id": 4056,
          "address_full": "văn phú tĩnh, Thị trấn Phố Bảng, Huyện Đồng Văn, Tỉnh Hà Giang",
          "type_register": null,
          "is_active": 1,
          "email": "li@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Tại cửa hàng",
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      },
      {
          "member_id": "450310",
          "customer_code": "SM22051000001                                     ",
          "full_name": "Test ",
          "gender": 0,
          "birth_day": "05/02/2022",
          "phone_number": "09898767584",
          "customer_type_name": "Khách hàng vàng",
          "customer_type_id": 3054,
          "address_full": "62 yên phụ  tt, Phường Yết Kiêu, Quận Hà Đông, Tỉnh Cao Bằng",
          "type_register": null,
          "is_active": 1,
          "email": "mai@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": null,
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      },
      {
          "member_id": "440310",
          "customer_code": "SM22050600001                                     ",
          "full_name": "Nguyen Thi Thu Trang",
          "gender": 1,
          "birth_day": "28/06/1998",
          "phone_number": "0346508755",
          "customer_type_name": "Khách hàng đồng",
          "customer_type_id": 3056,
          "address_full": "200, abc, Phường Cống Vị, Quận Ba Đình, Thành phố Hà Nội",
          "type_register": null,
          "is_active": 1,
          "email": "huuhai810@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Website",
          "anni_ver": "27/06/1998",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      },
      {
          "member_id": "440310",
          "customer_code": "SM22050600001                                     ",
          "full_name": "Nguyen Thi Thu Trang",
          "gender": 1,
          "birth_day": "28/06/1998",
          "phone_number": "0346508755",
          "customer_type_name": "Khách hàng đồng",
          "customer_type_id": 3056,
          "address_full": "200, abc, Phường Cống Vị, Quận Ba Đình, Thành phố Hà Nội",
          "type_register": null,
          "is_active": 1,
          "email": "huuhai810@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Website",
          "anni_ver": "27/06/1998",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "440310",
          "customer_code": "SM22050600001                                     ",
          "full_name": "Nguyen Thi Thu Trang",
          "gender": 1,
          "birth_day": "28/06/1998",
          "phone_number": "0346508755",
          "customer_type_name": "Khách hàng đồng",
          "customer_type_id": 3056,
          "address_full": "200, abc, Phường Cống Vị, Quận Ba Đình, Thành phố Hà Nội",
          "type_register": null,
          "is_active": 1,
          "email": "huuhai810@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Website",
          "anni_ver": "27/06/1998",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "430310",
          "customer_code": "SM22050500002                                     ",
          "full_name": "Vũ Phước Thạch",
          "gender": 1,
          "birth_day": "12/07/2021",
          "phone_number": "0968981265",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "1137/1 Kha Vạn Cân, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "vophuocminhhao1997@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Tại cửa hàng",
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "adasd"
      },
      {
          "member_id": "430310",
          "customer_code": "SM22050500002                                     ",
          "full_name": "Vũ Phước Thạch",
          "gender": 1,
          "birth_day": "12/07/2021",
          "phone_number": "0968981265",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "1137/1 Kha Vạn Cân, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "vophuocminhhao1997@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Tại cửa hàng",
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "430310",
          "customer_code": "SM22050500002                                     ",
          "full_name": "Vũ Phước Thạch",
          "gender": 1,
          "birth_day": "12/07/2021",
          "phone_number": "0968981265",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "1137/1 Kha Vạn Cân, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "vophuocminhhao1997@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Tại cửa hàng",
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      },
      {
          "member_id": "420311",
          "customer_code": "SM22050500001                                     ",
          "full_name": "Ngô Minh Hiếu",
          "gender": 1,
          "birth_day": "28/06/1998",
          "phone_number": "0123444441",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Xã Ngọc Khê, Huyện Trùng Khánh, Tỉnh Cao Bằng, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "test456@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Zalo",
          "anni_ver": "27/06/1998",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      },
      {
          "member_id": "420311",
          "customer_code": "SM22050500001                                     ",
          "full_name": "Ngô Minh Hiếu",
          "gender": 1,
          "birth_day": "28/06/1998",
          "phone_number": "0123444441",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Xã Ngọc Khê, Huyện Trùng Khánh, Tỉnh Cao Bằng, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "test456@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Zalo",
          "anni_ver": "27/06/1998",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "420311",
          "customer_code": "SM22050500001                                     ",
          "full_name": "Ngô Minh Hiếu",
          "gender": 1,
          "birth_day": "28/06/1998",
          "phone_number": "0123444441",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Xã Ngọc Khê, Huyện Trùng Khánh, Tỉnh Cao Bằng, Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "test456@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Zalo",
          "anni_ver": "27/06/1998",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày sinh nhật"
      },
      {
          "member_id": "380319",
          "customer_code": "SM22042600010                                     ",
          "full_name": "Nguyễn Lành Thiện ",
          "gender": 0,
          "birth_day": "04/06/2022",
          "phone_number": "7899876765",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "thien@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Tại cửa hàng",
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      },
      {
          "member_id": "380318",
          "customer_code": "SM22042600009                                     ",
          "full_name": "Nguyễn Thiện Lành",
          "gender": 0,
          "birth_day": "04/01/2022",
          "phone_number": "0987564565",
          "customer_type_name": null,
          "customer_type_id": null,
          "address_full": "Việt Nam",
          "type_register": null,
          "is_active": 1,
          "email": "lanh@gmail.com",
          "status_data_leads_key": "NOT_ASSIGNED",
          "status_data_leads_name": "Chưa phân công việc",
          "status_data_leads_id": 2,
          "customer_company_name": null,
          "caring_user": null,
          "caring_user_name": null,
          "zalo_id": null,
          "number_order": 0,
          "number_product_order": 0,
          "source_name": "Tại cửa hàng",
          "anni_ver": "01/01/1900",
          "time_final_buy": null,
          "customer_care_type_name": "Chăm sóc ngày kỷ niệm "
      }
  ],
  "totalItems": 116,
  "page": "1",
  "totalPages": 5,
  "itemsPerPage": "25"
}
